name: "Gadget Deploy from Subfolder"
description: "Deploy a Gadget app using CLI from a specified path"
inputs:
  app:
    description: "Gadget app name"
    required: true
  environment:
    description: "Gadget environment"
    required: true
  token:
    description: "Gadget CLI token"
    required: true
  path:
    description: "Path to the Gadget app folder"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Gadget CLI
      shell: bash
      run: npm install -g @gadgetinc/ggt

    - name: Deploy Gadget App
      shell: bash
      run: |
        export GGT_TOKEN="${{ inputs.token }}"
        ggt deploy --app "${{ inputs.app }}" --environment "${{ inputs.environment }}" --allow-issues true --allow-unknown-directory
