name: "Gadget Deploy from Subfolder"
description: "Deploy a Gadget app using CLI from a specified path"
inputs:
  environment:
    description: "Gadget environment"
    required: true
  token:
    description: "Gadget CLI token"
    required: true
  path:
    description: "Path to the Gadget app folder"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Gadget CLI
      run: npm install -g @gadgetinc/ggt

    - name: Deploy Gadget App
      shell: bash
      run: |
        cd "${{ inputs.path }}"
        echo "Current directory: $(pwd)"
        export GGT_TOKEN="${{ inputs.token }}"
        ggt deploy --environment "${{ inputs.environment }}" --allow-issues true
        
